### ISSUE TITLE
xauthみたいな認証が欲しい(？)

### ISSUE THREAD

**Issue by ghostrick** [Kekun321R/TwitterAPI-for-CSharp-oauth-#7]
これ
http://qiita.com/leafia78/items/5de99ab104ec83cf3a42

**Comment by rf0321** [comment]
Issue今確認しました。ConsumerKey取得するサイトでAccessTokenとAccessTokenSecretを確認できるのであまり考えてませんでした。キーを返すメソッドを追加する感じですか？
